# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: zkexpress
service: ai-service

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-3
  stage: dev
  timeout: 30

functions:
  app:
    handler: handler.handler
    timeout: 30
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    environment:
      RPC_URL: ${env:RPC_URL}
      PRIVATE_KEY: ${env:PRIVATE_KEY}
      REGISTRY_CONTRACT_ADDRESS: ${env:REGISTRY_CONTRACT_ADDRESS}
      ORDER_HISTORY_CONTRACT_ADDRESS: ${env:ORDER_HISTORY_CONTRACT_ADDRESS}
      ASI_API_KEY: ${env:ASI_API_KEY}

